# Total number of labeled samples
data: 
  num_labeled: 250

steps:
  updates: 1024
  epochs: 250
  test_epoch: 10

hp:
  bs: 64
  wd: 0.0005
  lr: 0.03

ref:
  threshold: 0.95
  τ: 0.333
  μ: 7
  α: 0.05
  order: 2
  particles: 4


seed: 0
num_workers: 4
